# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlpineBI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RSSelectionMenu', '~> 6.1.0'
  pod 'CropViewController'
end
